### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by tzussman**
There's a lot of small fixes and cleanup here, among them:

- Getting rid of the code graveyard (still exists in git history if necessary, but preferable to not have large chunks of commented out code in production)
- Switching from `.format()` to f-string formatting, as it is preferred in Python 3.7+ and we don't support Python 3.6 or lower
- Splitting up long strings using implicit string concatenation to avoid very long lines/comments
- Fix the cli's download functionality (was using wrong functions)
- Remove the original `download_tar_file()` function, as it was unused, and rename `download_file()` to `download_tar_file()`, as it is a more accurate description
- Clean up and reorder imports according to convention (std library, third-party, local imports - first those using `import` and then using `from ... import ...`)
- Fix `scipy.ndimage.morphology` import deprecation warning
- A few more formatting and simplification changes

### CODE REVIEW

**Comment by jonschwenk** [comment]
Looks like a bunch of JSON decoder errors (presumably related to string creation or parsing changes?) on the test builds...can you track down the source? Did you run the tests locally without issue?

**Comment by tzussman** [comment]
Tests passed in my fork: https://github.com/tzussman/rabpro/actions/runs/2719107210

**Comment by jonschwenk** [comment]
It looks to me like the builds are failing because of invalid GEE credentials. I'm tempted to merge the PRs since the credentials are not an issue in the Main branch builds. I assume that these being PRs has something to do with invalid credentials...thoughts?

**Comment by jsta** [comment]
Big fan of fixing that scipy deprecation warning!

**Comment by jonschwenk** [comment]
@jsta looking at the fix, it appears to be a simple import change. I suspect you're referring to a different warning but not sure.

**Comment by jonschwenk** [comment]
The other merge was fine, so here we go!

**Pull request merged**
