### PR TITLE
Clean tests

### PR DESCRIPTION
**Pull request by tzussman**
This gets rid of some of the old test infrastructure and outdated scripts

### CODE REVIEW

**Comment by tzussman** [comment]
It seems like the earth-engine credentials weren't accepted in CI...

**Comment by jonschwenk** [comment]
Same JSON decoder issues--is this problem related to the credentials somehow?

**Comment by tzussman** [comment]
Yep, all of these are failing due at the `ee.Initialize()` call, which is failing for some credentials-related reason.
I ran the tests for this and the other PR locally with earthengine authentication, but I don't have the MERIT data at the moment, so three of them (`test_rebuild_vrts.py` and `test_vector_pipeline.py`) failed due to that. However, the only ones that failed in CI are the earthengine related ones, and all of those pass for me locally.

I'm running the tests in my fork, will post link here once they complete (seems good so far)

**Comment by tzussman** [comment]
Tests passed in my fork: https://github.com/tzussman/rabpro/actions/runs/2719105188

**Comment by tzussman** [comment]
It's possible the credentials located in the repo's secret store have expired... Coincidentally it's been just about a year since they were added...

**Comment by jonschwenk** [comment]
I don't think the secret expires (although it was created on 7/19 last year). I did see this at the top of the secrets page: 

> Secrets are not passed to workflows that are triggered by a pull request from a fork. 

That makes sense, and is probably why these are failing. Let's merge and see what happens.

**Pull request merged**
