### PR TITLE
Data cleanup

### PR DESCRIPTION
**Pull request by tzussman**
- Remove `get_hydrobasins.py` and `get_merit_dem.py` scripts, as this functionality is available in rabpro and in the CLI
- ~Remove the `Data/HydroBasins` and `Data/MERIT_Hydro` directories, as these are no longer used and can be created in the appropriate location both in rabpro and the CLI~
- ~Remove `Data` files from `.gitignore`~

I wanted to rename the directory from `Data` to `data`, but we have hardcoded URLs which require the Data form... Unfortunate, but not worth breaking anything over this

### CODE REVIEW

**Comment by jsta** [comment]
I liked having the Data directory as an example of the structure expected by rabpro but I'll defer to the will of the community.

**Comment by jonschwenk** [comment]
I think I'm with @jsta on keeping the Data subdirectories. Many of our potential users will appreciate all the examples they can get...@tzussman can you roll those back and resubmit?

**Comment by tzussman** [comment]
Yep, will do!

**Comment by tzussman** [comment]
@jonschwenk @jsta ready for re-review

**Pull request merged**
