### PR TITLE
Unpin geopandas and pin pyproj

### LINKED ISSUE #53: Unpin geopandas dependency
See https://github.com/jonschwenk/RivGraph/pull/60

### PR DESCRIPTION
**Pull request by tzussman**
Resolves #53

### CODE REVIEW

**Comment by jonschwenk** [comment]
Can we force the build check before merging this? I just want to make sure it doesn't break the build.

**Comment by jsta** [comment]
We can have the CI build run if we add `environment.yml` to the watched paths here https://github.com/VeinsOfTheEarth/rabpro/blob/main/.github/workflows/build.yaml#L14

**Comment by tzussman** [comment]
Ran it in my fork: https://github.com/tzussman/rabpro/runs/7469745944
Passes on macOS, but not Ubuntu... will try to investigate some more

**Comment by jonschwenk** [comment]
@tzussman any updates on the Ubuntu build?

**Comment by tzussman** [comment]
I ran this locally on my Linux VM and everything was fine, but the Github build still didn't work...
I'm really not sure why it worked locally but not in actions, but I changed from using miniconda to using mamba in 1d0ede0, which seemed to make everything work (see [run in my fork](https://github.com/tzussman/rabpro/runs/7567383858))

**Comment by jsta** [comment]
I'll try creating the env on my local Ubuntu machine. I say if that's successful we merge.

**Comment by jsta** [comment]
Works on my machine, fingers crossed it also works for conda-forge

**Pull request merged**
